# Generated by Django 3.0.3 on 2020-02-25 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Text', models.CharField(max_length=140)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
    ]
