# Generated by Django 3.0.3 on 2020-02-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='Text',
            new_name='text',
        ),
    ]
